### ISSUE TITLE
restart notification

### ISSUE THREAD

**Issue by angelochen960** [foreversd/forever#301]
Hi,
when something goes wrong and forever restart the node app, is there a way to be notified about this restarting?
thanks,
angelo

**Comment by sinsunsan** [comment]
Trying to do the solution described by @evgeny-goldin but could you be more explicit about  For that forever needs to run using --pidFile option.

forever server.js --pidFile 
?
How does it behave differently that without it (the forever doc)

When you write 

check process node with pidfile /home/user/.forever/pids/my.pid

my.pid is to be replaced by What ? 

With your solution, you only have the info, my node server has restarted, not why ? Would be nice that it change its log at each restart so that, it suffice to look at the bottom of the file. 


@sdolard is node-crashreporter still a actual project, is there a better solution now ? 
How to use it with forever ?

**Comment by roysG** [comment]
any updated about that?

**Comment by priyankinfinnov** [comment]
Is this going to be done ?
And have you guys found any work around ?

**Comment by benediktdertinger** [comment]
+1

**Comment by F3L1X79** [comment]
Same here, I want to receive a mail on crash, but it's really hard to find a working implementation example of this.

**Comment by 4ley** [comment]
+1

**Comment by GerbenHofman** [comment]
+1

**Comment by amitjain04** [comment]
+1 
Is it available now?

**Comment by tamsler** [comment]
+1

**Comment by OmarKan** [comment]
+1

**Comment by rejhgadellaa** [comment]
+1

**Comment by tamaker** [comment]
+1

**Comment by rejhgadellaa** [comment]
+1
