### ISSUE TITLE
Log files are not created relative to the current working directory

### ISSUE THREAD

**Issue by fresheneesz** [foreversd/forever#438]
Every other command line process in the universe treats file path as relative to the current working directory. Please follow that standard. To be extra clear, the following should create a file called "forever.log" in the current working directory:

```
forever -l forever.log start whatever.js
```

**Comment by MichaelPin** [comment]
Just an FYI: it's still the case on my Linux setup in 2023. Log file from forever is created under user home directory.
It's nothing too serious and can be worked around by supplying log file path like so:
`-l "$PWD"/forever.log`. Still, it's pretty odd, since `-o` and `-e` create files with relative paths.
This also seems like the intended behavior since forever will refuse to start if the log file is present.

Maybe adding another flag on the console would be a good solution? That would toggle relative path vs absolute(relative to forever config in user home). Something like `--relative-log-file`
