### ISSUE TITLE
error:   Forever cannot find process with id

### ISSUE THREAD

**Issue by bitliner** [foreversd/forever#636]
My app is currently running, let's say its name is name.js.

If I run `forever list`, it shows name.js related entry.

But if I run `forever stop name.js` it throws

```
error:   Forever cannot find process with id: name.js
```

If I look at `ps aux` output, it shows one entry for the currently running name.js app, and one entry for the monitor process.

Versions:
node:  0.10.33 
npm: 1.4.28 
forever: 0.13.0

**Comment by Dzenly** [comment]
Still facing this problem. Have to use "forever stop fullPath".

**Comment by NextZeus** [comment]
forever start --uid 'hello-world' 
forever stop 'hello-world'  is right, but forever stop hello-world is error. 

so i think , you need to start 'name' and stop 'name' ;

**Comment by tangshuang** [comment]
Only `forever stopall ` works, I have tried almost case and found stop is broken.

**Comment by spritecoco** [comment]
I have the same problem. Have you solved it?

**Comment by snowdream** [comment]
+1

**Comment by Kazanz** [comment]
+1 This is a real problem

<img width="1345" alt="screen shot 2018-08-02 at 10 13 57 pm" src="https://user-images.githubusercontent.com/7441147/43620579-68fbf11e-96a1-11e8-8f2b-4dd91d7ced13.png">

**Comment by gh-andre** [comment]
Running `forever` v3.0.4 and the bug is still there. Posting a couple of observations in case if anybody is still using `forever` with older apps.

It appears that it records the working directory when `start` runs and then expects `stop` to be executed from that directory. So, this works for script `/srv/myapp/dist/main.js` (`tmp` is out of place on purpose, to demonstrate the issue; must be absolute path in `--workingDir` and will fail with `~`):

    mkdir ~/tmp
    cd /srv/myapp
    forever start -p /path/to/uid/log --sourceDir=/srv/myapp/ --workingDir=/home/user1/tmp dist/main.js
    forever list

With this setup, I can only stop the script if the current directory is what was in `--workingDir` when it was started, so this works:

    cd /home/user1/tmp
    forever stop dist/main.js

Looks like there are some undocumented assumptions made and recorded when starting a Node app.

The most straightforward way to stop the app is use `--uid`, but for some inexplicable reason it was deprecated, so the next best thing is to use `--pidFile`. The docs misleadingly say PID files are stored in the directory pointed to by `-p`, but only `uid` log goes there and relative PID files go to `~/.forever/pids` (or where `forever config` shows as `pidPath`). 

So, this works reliably to stop a running script without having to worry about current directory.

    forever start -p /path/to/uid/log --sourceDir=/srv/myapp/ --pidFile=myapp.pid dist/main.js
    forever stop $(cat ~/.forever/pids/myapp.pid)
