### ISSUE TITLE
Still In Maintaining?

### ISSUE THREAD

**Issue by Tjatse** [foreversd/forever#650]
I've just wrote an elegant [web interface](https://github.com/Tjatse/forever-web) for forever, is this amazing tool still in maintaining?

> Actually when we are stopping the STOPPED process, it will lead to crash, can you fix this emergent problem?  It's solved now, just need to do a `npm pub`.

@indexzero

**Comment by adamreisnz** [comment]
Hi @Tjatse , is anyone maintaining this package at present? There's a lot of open issues and last release was 10 months ago.

Now I understand people get busy and have other things to do, but are there any other contributors that could help/take over some of the development on this package? It's used a lot and it'd be sad to have it come to an end because there's no one to maintain it.
